name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow"
database_id = "8c6d2232-113e-49f9-b01a-c0db289b3aa8"
